jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/circleci-demo-schedule
    steps:
      - checkout
      - run:
          name: Run Build Command
          command: echo "hello I am building and testing"
          
  deploy:
    docker:
      - image: circleci/node
    working_directory: ~/circleci-demo-schedule
    steps:
      - checkout
      - run:
          name: Run Deploy Command
          command: echoh "hello I am deploying"
          
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  schedule-workflow:
    triggers:
      - schedule:
          cron: "*/5 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build
      - deploy

       
